===2017-02-17 16:35:22.972 WARN  org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator Line:132 - HHH000342: Could not obtain connection to query metadata : Unknown database 'lawyer_base'
===2017-02-17 16:35:23.417 WARN  org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext Line:549 - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: @OneToOne or @ManyToOne on com.xia.lawyer.models.system.UserDetail.user references an unknown entity: com.xia.lawyer.models.system.User
===2017-02-17 16:38:43.943 WARN  org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext Line:549 - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration': Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'writeDataSource' defined in class path resource [com/xia/lawyer/druid/DruidDataSource.class]: Invocation of init method failed; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'lawyer_base'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'writeDataSource' defined in class path resource [com/xia/lawyer/druid/DruidDataSource.class]: Invocation of init method failed; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'lawyer_base'
===2017-02-17 16:40:31.128 WARN  org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext Line:549 - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: @OneToOne or @ManyToOne on com.xia.lawyer.models.system.UserDetail.user references an unknown entity: com.xia.lawyer.models.system.User
===2017-02-17 16:41:15.068 WARN  org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext Line:549 - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: @OneToOne or @ManyToOne on com.xia.lawyer.models.system.UserDetail.user references an unknown entity: com.xia.lawyer.models.system.User
===2017-02-17 16:43:17.181 WARN  org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext Line:549 - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: @OneToOne or @ManyToOne on com.xia.lawyer.models.system.UserDetail.user references an unknown entity: com.xia.lawyer.models.system.User
===2017-02-17 16:45:45.276 WARN  org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext Line:549 - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: mappedBy reference an unknown target entity property: com.xia.lawyer.models.system.User.user in com.xia.lawyer.models.system.Department.users
===2017-02-17 16:51:15.650 WARN  org.hibernate.id.UUIDHexGenerator Line:42  - HHH000409: Using org.hibernate.id.UUIDHexGenerator which does not generate IETF RFC 4122 compliant UUID values; consider using org.hibernate.id.UUIDGenerator instead
===2017-02-17 17:01:09.261 WARN  org.hibernate.id.UUIDHexGenerator Line:42  - HHH000409: Using org.hibernate.id.UUIDHexGenerator which does not generate IETF RFC 4122 compliant UUID values; consider using org.hibernate.id.UUIDGenerator instead
===2017-02-17 17:03:04.081 WARN  org.hibernate.id.UUIDHexGenerator Line:42  - HHH000409: Using org.hibernate.id.UUIDHexGenerator which does not generate IETF RFC 4122 compliant UUID values; consider using org.hibernate.id.UUIDGenerator instead
